# Generated by Django 5.2.5 on 2025-08-09 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of pickup/drop-off locations, Google Maps links, or special instructions'),
        ),
        migrations.AlterField(
            model_name='route',
            name='base_price_zar',
            field=models.DecimalField(decimal_places=2, help_text='Base price in South African Rand (ZAR)', max_digits=10, validators=[django.core.validators.MinValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(help_text='Distance in kilometers', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration_hours',
            field=models.FloatField(help_text='Travel time in hours', validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(check=~models.Q(origin=models.F('destination')), name='different_origin_destination'),
        ),
    ]
