# Generated by Django 5.2.5 on 2025-08-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_route_description_alter_route_base_price_zar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='operating_days',
            field=models.CharField(default='Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday', help_text='Comma-separated list of operating days (e.g., "Monday,Wednesday,Friday")', max_length=100),
        ),
    ]
