# Generated by Django 5.2.5 on 2025-08-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_route_operating_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(default='FB000000', editable=False, help_text='Human-readable booking reference (e.g., FB123456)', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Passenger date of birth', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact name', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20),
        ),
    ]
