# Generated by Django 5.2.5 on 2025-08-10 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_booking_booking_reference_booking_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid South African phone number (e.g., 083 123 4567 or +27 83 123 4567)', regex='^(\\+27|0)[0-9\\s]{9,12}$')]),
        ),
    ]
