# Generated by Django 5.2.5 on 2025-08-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_booking_passenger_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, editable=False, help_text='Human-readable booking reference (e.g., FB123456)', max_length=15, null=True, unique=True),
        ),
    ]
