# Generated by Django 5.2.5 on 2025-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_booking_booking_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount in ZAR', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('scholar', 'Scholar (13 years & younger)'), ('student', 'Student (Student card required)'), ('pensioner', 'Pensioner (ID required)')], default='none', help_text='Type of discount applied', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Original amount before discount', max_digits=10),
        ),
    ]
