# Generated by Django 5.2.5 on 2025-08-10 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_booking_discount_amount_booking_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(help_text='Contact phone number (any international format accepted)', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number (e.g., +27 83 123 4567, 083 123 4567, +82 10 1234 5678)', regex='^[\\+]?[0-9\\s\\-\\(\\)]{7,20}$')]),
        ),
    ]
