# Generated by Django 5.2.5 on 2025-08-10 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_alter_booking_passenger_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_seats',
            field=models.IntegerField(default=1, help_text='Number of seats being booked (fixed to 1 per booking)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
