# Generated by Django 5.0 on 2025-08-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_alter_booking_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_failure_reason',
            field=models.TextField(blank=True, help_text='Reason for payment failure (if applicable)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_client_secret',
            field=models.CharField(blank=True, help_text='Stripe client secret for frontend payment confirmation', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='Stripe payment method ID', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_processing', 'Payment Processing'), ('payment_failed', 'Payment Failed'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending_payment', help_text='Current status of the booking', max_length=20),
        ),
    ]
