# Generated by Django 5.0 on 2025-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_booking_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_client_secret',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stripe_payment_method_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='payfast_payment_id',
            field=models.CharField(blank=True, help_text='PayFast payment ID for tracking', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payfast_payment_status',
            field=models.CharField(blank=True, help_text='PayFast payment status (COMPLETE, FAILED, CANCELLED)', max_length=50, null=True),
        ),
    ]
