# Generated by Django 5.2.5 on 2025-08-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_remove_booking_stripe_client_secret_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='booking_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['passenger_email'], name='booking_email_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['schedule', 'status'], name='booking_schedule_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='booking_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payfast_payment_id'], name='booking_payment_id_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin'], name='route_origin_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['destination'], name='route_dest_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination'], name='route_origin_dest_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='route_active_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['base_price_zar'], name='route_price_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['departure_time'], name='schedule_departure_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['route', 'departure_time'], name='schedule_route_time_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['is_active', 'departure_time'], name='schedule_active_time_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['available_seats'], name='schedule_seats_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['bus'], name='schedule_bus_idx'),
        ),
    ]
